apiVersion: v1
kind: Service
metadata:
  labels:
    jenkins-app: jenkins-mike-react-app
  name: jenkins-mike-react-service
  namespace: jenkins
spec:
  type: NodePort
  selector:
    jenkins-app: jenkins-mike-react-app
  ports:
  - port: 80 
    targetPort: 80
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    jenkins-app: jenkins-mike-react-app
  name: jenkins-mike-react
  namespace: jenkins
spec:
  replicas: 3
  selector:
    matchLabels:
      jenkins-app: jenkins-mike-react-app
  template:
    metadata:
      labels:
        jenkins-app: jenkins-mike-react-app
    spec:
      containers:
        - name: jenkins-react
          image: mrg34dck/react-container-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: '128Mi'
              cpu: '200m'
          livenessProbe:
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 1
          readinessProbe:
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 1
